// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock_metastore

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	streamingpb "github.com/milvus-io/milvus/pkg/v2/proto/streamingpb"
)

// MockReplicationCatalog is an autogenerated mock type for the ReplicationCatalog type
type MockReplicationCatalog struct {
	mock.Mock
}

type MockReplicationCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplicationCatalog) EXPECT() *MockReplicationCatalog_Expecter {
	return &MockReplicationCatalog_Expecter{mock: &_m.Mock}
}

// ListReplicatePChannels provides a mock function with given fields: ctx
func (_m *MockReplicationCatalog) ListReplicatePChannels(ctx context.Context) ([]*streamingpb.ReplicatePChannelMeta, []int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListReplicatePChannels")
	}

	var r0 []*streamingpb.ReplicatePChannelMeta
	var r1 []int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*streamingpb.ReplicatePChannelMeta, []int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*streamingpb.ReplicatePChannelMeta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*streamingpb.ReplicatePChannelMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []int64); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]int64)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReplicationCatalog_ListReplicatePChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReplicatePChannels'
type MockReplicationCatalog_ListReplicatePChannels_Call struct {
	*mock.Call
}

// ListReplicatePChannels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReplicationCatalog_Expecter) ListReplicatePChannels(ctx interface{}) *MockReplicationCatalog_ListReplicatePChannels_Call {
	return &MockReplicationCatalog_ListReplicatePChannels_Call{Call: _e.mock.On("ListReplicatePChannels", ctx)}
}

func (_c *MockReplicationCatalog_ListReplicatePChannels_Call) Run(run func(ctx context.Context)) *MockReplicationCatalog_ListReplicatePChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReplicationCatalog_ListReplicatePChannels_Call) Return(_a0 []*streamingpb.ReplicatePChannelMeta, _a1 []int64, _a2 error) *MockReplicationCatalog_ListReplicatePChannels_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReplicationCatalog_ListReplicatePChannels_Call) RunAndReturn(run func(context.Context) ([]*streamingpb.ReplicatePChannelMeta, []int64, error)) *MockReplicationCatalog_ListReplicatePChannels_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReplicatePChannelWithVersion provides a mock function with given fields: ctx, meta, Version
func (_m *MockReplicationCatalog) RemoveReplicatePChannelWithVersion(ctx context.Context, meta *streamingpb.ReplicatePChannelMeta, Version int64) (bool, error) {
	ret := _m.Called(ctx, meta, Version)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReplicatePChannelWithVersion")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *streamingpb.ReplicatePChannelMeta, int64) (bool, error)); ok {
		return rf(ctx, meta, Version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *streamingpb.ReplicatePChannelMeta, int64) bool); ok {
		r0 = rf(ctx, meta, Version)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *streamingpb.ReplicatePChannelMeta, int64) error); ok {
		r1 = rf(ctx, meta, Version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReplicatePChannelWithVersion'
type MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call struct {
	*mock.Call
}

// RemoveReplicatePChannelWithVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *streamingpb.ReplicatePChannelMeta
//   - Version int64
func (_e *MockReplicationCatalog_Expecter) RemoveReplicatePChannelWithVersion(ctx interface{}, meta interface{}, Version interface{}) *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call {
	return &MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call{Call: _e.mock.On("RemoveReplicatePChannelWithVersion", ctx, meta, Version)}
}

func (_c *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call) Run(run func(ctx context.Context, meta *streamingpb.ReplicatePChannelMeta, Version int64)) *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*streamingpb.ReplicatePChannelMeta), args[2].(int64))
	})
	return _c
}

func (_c *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call) Return(_a0 bool, _a1 error) *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call) RunAndReturn(run func(context.Context, *streamingpb.ReplicatePChannelMeta, int64) (bool, error)) *MockReplicationCatalog_RemoveReplicatePChannelWithVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReplicationCatalog creates a new instance of MockReplicationCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplicationCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplicationCatalog {
	mock := &MockReplicationCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
