package attributes

import (
	"github.com/milvus-io/milvus/internal/proto/streamingpb"
	"github.com/milvus-io/milvus/internal/util/sessionutil"
	"google.golang.org/grpc/attributes"
)

type attributesKeyType int

const (
	serverIDKey attributesKeyType = iota
	channelAssignmentInfoKey
	sessionKey
)

type Attributes = attributes.Attributes

// GetServerID returns the serverID in the given Attributes.
func GetServerID(attr *Attributes) *int64 {
	val := attr.Value(serverIDKey)
	if val == nil {
		return nil
	}
	serverID := val.(int64)
	return &serverID
}

// WithChannelAssignmentInfo returns a new Attributes containing the given channelInfo.
func WithChannelAssignmentInfo(attr *Attributes, assignment *streamingpb.StreamingNodeAssignment) *attributes.Attributes {
	return attr.WithValue(channelAssignmentInfoKey, assignment).WithValue(serverIDKey, assignment.ServerId)
}

// GetChannelAssignmentInfoFromAttributes get the channel info fetched from streamingcoord.
// Generated by the channel assignment discoverer and sent to channel assignment balancer.
func GetChannelAssignmentInfoFromAttributes(attrs *Attributes) *streamingpb.StreamingNodeAssignment {
	val := attrs.Value(channelAssignmentInfoKey)
	if val == nil {
		return nil
	}
	return val.(*streamingpb.StreamingNodeAssignment)
}

// WithSession returns a new Attributes containing the given session.
func WithSession(attr *Attributes, val *sessionutil.Session) *attributes.Attributes {
	return attr.WithValue(sessionKey, val).WithValue(serverIDKey, val.ServerID)
}

// GetSessionFromAttributes get session from attributes.
func GetSessionFromAttributes(attrs *Attributes) *sessionutil.Session {
	val := attrs.Value(sessionKey)
	if val == nil {
		return nil
	}
	return val.(*sessionutil.Session)
}
