// Code generated by mockery v2.53.3. DO NOT EDIT.

package replication

import mock "github.com/stretchr/testify/mock"

// MockReplicateManagerClient is an autogenerated mock type for the ReplicateManagerClient type
type MockReplicateManagerClient struct {
	mock.Mock
}

type MockReplicateManagerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplicateManagerClient) EXPECT() *MockReplicateManagerClient_Expecter {
	return &MockReplicateManagerClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockReplicateManagerClient) Close() {
	_m.Called()
}

// MockReplicateManagerClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReplicateManagerClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReplicateManagerClient_Expecter) Close() *MockReplicateManagerClient_Close_Call {
	return &MockReplicateManagerClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReplicateManagerClient_Close_Call) Run(run func()) *MockReplicateManagerClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplicateManagerClient_Close_Call) Return() *MockReplicateManagerClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReplicateManagerClient_Close_Call) RunAndReturn(run func()) *MockReplicateManagerClient_Close_Call {
	_c.Run(run)
	return _c
}

// CreateReplicator provides a mock function with given fields: replicateKey, repCtx
func (_m *MockReplicateManagerClient) CreateReplicator(replicateKey string, repCtx *ReplicateContext) {
	_m.Called(replicateKey, repCtx)
}

// MockReplicateManagerClient_CreateReplicator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReplicator'
type MockReplicateManagerClient_CreateReplicator_Call struct {
	*mock.Call
}

// CreateReplicator is a helper method to define mock.On call
//   - replicateKey string
//   - repCtx *ReplicateContext
func (_e *MockReplicateManagerClient_Expecter) CreateReplicator(replicateKey interface{}, repCtx interface{}) *MockReplicateManagerClient_CreateReplicator_Call {
	return &MockReplicateManagerClient_CreateReplicator_Call{Call: _e.mock.On("CreateReplicator", replicateKey, repCtx)}
}

func (_c *MockReplicateManagerClient_CreateReplicator_Call) Run(run func(replicateKey string, repCtx *ReplicateContext)) *MockReplicateManagerClient_CreateReplicator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*ReplicateContext))
	})
	return _c
}

func (_c *MockReplicateManagerClient_CreateReplicator_Call) Return() *MockReplicateManagerClient_CreateReplicator_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReplicateManagerClient_CreateReplicator_Call) RunAndReturn(run func(string, *ReplicateContext)) *MockReplicateManagerClient_CreateReplicator_Call {
	_c.Run(run)
	return _c
}

// RemoveReplicator provides a mock function with given fields: replicateKey
func (_m *MockReplicateManagerClient) RemoveReplicator(replicateKey string) {
	_m.Called(replicateKey)
}

// MockReplicateManagerClient_RemoveReplicator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReplicator'
type MockReplicateManagerClient_RemoveReplicator_Call struct {
	*mock.Call
}

// RemoveReplicator is a helper method to define mock.On call
//   - replicateKey string
func (_e *MockReplicateManagerClient_Expecter) RemoveReplicator(replicateKey interface{}) *MockReplicateManagerClient_RemoveReplicator_Call {
	return &MockReplicateManagerClient_RemoveReplicator_Call{Call: _e.mock.On("RemoveReplicator", replicateKey)}
}

func (_c *MockReplicateManagerClient_RemoveReplicator_Call) Run(run func(replicateKey string)) *MockReplicateManagerClient_RemoveReplicator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockReplicateManagerClient_RemoveReplicator_Call) Return() *MockReplicateManagerClient_RemoveReplicator_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReplicateManagerClient_RemoveReplicator_Call) RunAndReturn(run func(string)) *MockReplicateManagerClient_RemoveReplicator_Call {
	_c.Run(run)
	return _c
}

// NewMockReplicateManagerClient creates a new instance of MockReplicateManagerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplicateManagerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplicateManagerClient {
	mock := &MockReplicateManagerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
