quiet: False
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: 'internal/mocks/{{trimPrefix .PackagePath "github.com/milvus-io/milvus/internal" | dir }}/mock_{{.PackageName}}'
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock_{{.PackageName}}"
resolve-type-alias: False
packages:
  github.com/milvus-io/milvus/internal/streamingcoord/server/balancer:
    interfaces:
      Balancer:
  github.com/milvus-io/milvus/internal/streamingcoord/server/broadcaster:
    interfaces:
      AppendOperator:
      Watcher:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors:
    interfaces:
      Interceptor:
      InterceptorWithReady:
      InterceptorWithMetrics:
      InterceptorBuilder:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/shard/shards:
    interfaces:
      ShardManager:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/shard/utils:
    interfaces:
      SealOperator:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector:
    interfaces:
      TimeTickSyncOperator:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/recovery:
    interfaces:
      RecoveryStorage:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/wab:
    interfaces:
      ROWriteAheadBuffer:
  github.com/milvus-io/milvus/internal/streamingnode/server/walmanager:
    interfaces:
      Manager:
  github.com/milvus-io/milvus/internal/metastore:
    interfaces:
      StreamingCoordCataLog:
      StreamingNodeCataLog:
  github.com/milvus-io/milvus/internal/util/segcore:
    interfaces:
      CSegment:
  github.com/milvus-io/milvus/internal/storage:
    interfaces:
      ChunkManager:
  github.com/milvus-io/milvus/internal/util/searchutil/optimizers:
    interfaces:
      QueryHook:
  github.com/milvus-io/milvus/internal/flushcommon/util:
    interfaces:
      MsgHandler:
  